function [WFMImg_31_ZmFOV,WFMImg_33_ZuNum,WFMImg_33_ZlNum,WFMImg_33_ZdNum,WFMImg_34_Z_Ind,WFMImg_35_ZCoor,...
          WFMSeg_38_Frm_Z,                WFMSeg_33_ZcNum,WFMSeg_33_ZdNum,WFMSeg_34_Z_Ind,WFMSeg_35_ZCoor,...
          FLFPSF_31_ZmFOV,FLFPSF_33_ZuNum,FLFPSF_33_ZlNum,FLFPSF_33_ZdNum,FLFPSF_34_Z_Ind,FLFPSF_35_ZCoor,...
          FLFRec_38_Frm_Z,                FLFRec_33_ZcNum,FLFRec_33_ZdNum,FLFRec_34_Z_Ind,FLFRec_35_ZCoor,...
          FLFImg_31_ZmFOV,FLFImg_33_ZuNum,FLFImg_33_ZlNum,FLFImg_33_ZdNum,FLFImg_34_Ind_Z,FLFImg_35_ZCoor,...
          FLFSeg_38_Z_Frm,                FLFSeg_33_ZcNum,FLFSeg_33_ZdNum,FLFSeg_34_Z_Ind,FLFSeg_35_ZCoor,...
          FLFImg_41_TmFOV,FLFImg_43_TuNum,FLFImg_43_TlNum,FLFImg_43_TdNum,FLFImg_44_T_Ind,FLFImg_45_TCoor,...
          FLFSeg_48_T_Frm,                FLFSeg_43_TcNum,FLFSeg_43_TdNum,FLFSeg_44_T_Ind,FLFSeg_45_TCoor,...
          FLFRec_03_MRaxi,FLFRec_04_MRmax,FLFRec_04_MRmin,FLFRec_03_fnum ,...
          FLFRec_13_Xrnum,FLFRec_13_XrNum,Recons_13_NumXc,FLFRec_13_XdNum,FLFRec_14_X_Ind,FLFRec_10_XCoor,...
          FLFRec_23_Yrnum,FLFRec_23_YrNum,Recons_23_NumYc,FLFRec_23_YdNum,FLFRec_24_Y_Ind,FLFRec_20_YCoor,...
          FLFRec_54_M_Ind,Path_s050_zrange] = S07_Coord_All(...
          WFMImg_31_ZuFOV,WFMImg_31_ZlFOV,WFMImg_32_Z_Stp,...
          WFMImg_31_ZuSeg,WFMImg_31_ZlSeg,WFMImg_31_Z_Seg,...
          FLFPSF_31_ZuFOV,FLFPSF_31_ZlFOV,FLFPSF_32_Z_Stp,...
          FLFRec_31_ZuFOV,FLFRec_31_ZlFOV,FLFRec_31_Z_Seg,...
          FLFImg_31_ZuFOV,FLFImg_31_ZlFOV,FLFImg_32_Z_Stp,...
          FLFImg_31_ZuSeg,FLFImg_31_ZlSeg,FLFImg_31_Z_Seg,...
          FLFImg_41_TuVid,FLFImg_41_TlVid,FLFImg_41_T_Stp,...
          FLFImg_41_TuSeg,FLFImg_41_TlSeg,FLFImg_41_T_Seg,...
          FLFRec_53_MrNum,Pi_05_cam,Pi_04_MLA,Ma_06_FLF,fn_06_FLF)
%     FLF_SimPSF_Simu_Stp = 0.4;
%     FLF_SimPSF_Simu_Ini = -150;
%     FLF_SimPSF_Simu_End = +150;
    
       [WFMImg_31_ZmFOV,WFMImg_33_ZuNum,WFMImg_33_ZlNum,...
        WFMImg_33_ZdNum,WFMImg_34_Z_Ind,WFMImg_35_ZCoor] = Coord_create_ud(WFMImg_31_ZuFOV,WFMImg_31_ZlFOV,WFMImg_32_Z_Stp);
        
       [WFMSeg_38_Frm_Z,WFMSeg_33_ZdNum,WFMSeg_33_ZcNum,WFMSeg_34_Z_Ind,WFMSeg_35_ZCoor] = Coord_Used(...
        WFMImg_31_ZlSeg,WFMImg_31_ZuSeg,WFMImg_31_Z_Seg,WFMImg_34_Z_Ind,WFMImg_35_ZCoor);

       [FLFPSF_31_ZmFOV,FLFPSF_33_ZuNum,FLFPSF_33_ZlNum,...
        FLFPSF_33_ZdNum,FLFPSF_34_Z_Ind,FLFPSF_35_ZCoor] = Coord_create_ud(FLFPSF_31_ZuFOV,FLFPSF_31_ZlFOV,FLFPSF_32_Z_Stp);
        
       [FLFRec_38_Frm_Z,FLFRec_33_ZdNum,FLFRec_33_ZcNum,FLFRec_34_Z_Ind,FLFRec_35_ZCoor] = Coord_Used(...
        FLFRec_31_ZlFOV,FLFRec_31_ZuFOV,FLFRec_31_Z_Seg,FLFPSF_34_Z_Ind,FLFPSF_35_ZCoor);
        
       [FLFImg_31_ZmFOV,FLFImg_33_ZuNum,FLFImg_33_ZlNum,...
        FLFImg_33_ZdNum,FLFImg_34_Ind_Z,FLFImg_35_ZCoor] = Coord_create_ud(FLFImg_31_ZuFOV,FLFImg_31_ZlFOV,FLFImg_32_Z_Stp);
        
       [FLFSeg_38_Z_Frm,FLFSeg_33_ZdNum,FLFSeg_33_ZcNum,FLFSeg_34_Z_Ind,FLFSeg_35_ZCoor] = Coord_Used(...
        FLFImg_31_ZlSeg,FLFImg_31_ZuSeg,FLFImg_31_Z_Seg,FLFImg_34_Ind_Z,FLFImg_35_ZCoor);
        
       [FLFImg_41_TmFOV,FLFImg_43_TuNum,FLFImg_43_TlNum,...
        FLFImg_43_TdNum,FLFImg_44_T_Ind,FLFImg_45_TCoor] = Coord_create_ud(FLFImg_41_TuVid,FLFImg_41_TlVid,FLFImg_41_T_Stp);
    
       [FLFSeg_48_T_Frm,FLFSeg_43_TdNum,FLFSeg_43_TcNum,FLFSeg_44_T_Ind,FLFSeg_45_TCoor] = Coord_Used(...
        FLFImg_41_TlSeg,FLFImg_41_TuSeg,FLFImg_41_T_Seg,FLFImg_44_T_Ind,FLFImg_45_TCoor);
        
        FLFRec_03_MRaxi = Ma_06_FLF*ones(1,FLFRec_33_ZdNum);               FLFRec_04_MRmax  = max( FLFRec_03_MRaxi );
        FLFRec_03_fnum  = fn_06_FLF*ones(1,FLFRec_33_ZdNum);               FLFRec_04_MRmin  = min( FLFRec_03_MRaxi );
        
        FLFRec_12_X_Stp =     Pi_05_cam                 /FLFRec_04_MRmax;
        FLFRec_22_Y_Stp =     Pi_05_cam                 /FLFRec_04_MRmax;
        
        FLFRec_13_Xrnum = fix(Pi_04_MLA/FLFRec_12_X_Stp./FLFRec_03_MRaxi/2);  FLFRec_13_Xdnum = 1+FLFRec_13_Xrnum*2;
        FLFRec_23_Yrnum = fix(Pi_04_MLA/FLFRec_22_Y_Stp./FLFRec_03_MRaxi/2);  FLFRec_23_Ydnum = 1+FLFRec_23_Yrnum*2;
        
        FLFRec_13_XrNum = max( FLFRec_13_Xrnum );                             FLFRec_13_XdNum = 1+FLFRec_13_XrNum*2;  Recons_13_NumXc = 1+FLFRec_13_XrNum;
        FLFRec_23_YrNum = max( FLFRec_23_Yrnum );                             FLFRec_23_YdNum = 1+FLFRec_23_YrNum*2;  Recons_23_NumYc = 1+FLFRec_23_YrNum;
        
        FLFRec_14_X_Ind = (-FLFRec_13_XrNum:FLFRec_13_XrNum);                 FLFRec_10_XCoor = FLFRec_14_X_Ind.* FLFRec_12_X_Stp;
        FLFRec_24_Y_Ind = (-FLFRec_23_YrNum:FLFRec_23_YrNum);                 FLFRec_20_YCoor = FLFRec_24_Y_Ind.* FLFRec_22_Y_Stp;
        FLFRec_54_M_Ind = (-FLFRec_53_MrNum:FLFRec_53_MrNum);
        
        Path_s050_zrange = ['zMmd_',num2str(FLFRec_31_ZlFOV*1e6,'%.0f'),  '_',...
                                    num2str(FLFRec_31_ZuFOV*1e6,'%.0f'),'um_',...
                                    num2str(FLFPSF_32_Z_Stp*1e9,'%03d'),'nm_'];
end


function [Object_31_FOVZm,Object_33_NumZu,Object_33_NumZl,...
          Object_33_NumZd,Object_34_Ind_Z,Object_35_CoorZ] = Coord_create_ud(Object_31_FOVZu,Object_31_FOVZl,Object_32_STP_Z)
% Object_31_FOVZu = +120.000*10^-6
% Object_31_FOVZl = -120.000*10^-6
% Object_32_STP_Z = Object_32_Z_stp
        
        Object_35_CoorZ = Object_31_FOVZl:Object_32_STP_Z:Object_31_FOVZu ; 
        Object_34_Ind_Z =          int32( Object_35_CoorZ/Object_32_STP_Z);  
        Object_33_NumZl =         Object_34_Ind_Z( 1 );  
        Object_33_NumZu =         Object_34_Ind_Z(end); 
        Object_33_NumZd =  length(Object_34_Ind_Z);
        Object_31_FOVZm = max(abs(Object_31_FOVZu),abs(Object_31_FOVZl));
end

function [ObjUse_08_frame,ObjUse_33_NumZd,ObjUse_33_NumZc,ObjUse_34_Ind_Z,ObjUse_35_CoorZ] = Coord_Used(...
          ObjUse_31_FOVZl,ObjUse_31_FOVZu,ObjUse_31_numsg,Object_34_Ind_Z,Object_35_CoorZ)              
%  ObjUse_31_FOVZl = FLFImg_41_TlSeg
%  ObjUse_31_FOVZu = FLFImg_41_TuSeg
%  ObjUse_31_numsg = FLFImg_41_T_Seg
%  Object_35_CoorZ = FLFImg_44_T_Ind
%  Object_34_Ind_Z = FLFImg_45_TCoor
        Object_35_CoorZ = double(Object_35_CoorZ);
        ObjUse_08_framt = find( (ObjUse_31_FOVZl-1e-10)<=Object_35_CoorZ & Object_35_CoorZ<=(ObjUse_31_FOVZu+1e-10) );
        ObjUse_08_frame = ObjUse_08_framt(1:ObjUse_31_numsg:end);          
        ObjUse_33_NumZd = length(ObjUse_08_frame)         ;                ObjUse_33_NumZc = ceil(ObjUse_33_NumZd/2); 
        ObjUse_34_Ind_Z = Object_34_Ind_Z(ObjUse_08_frame);                ObjUse_35_CoorZ = Object_35_CoorZ(ObjUse_08_frame);
end